{{- if and .Values.gitlab.token (not .Values.gitlab.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terrascaler.gitlabTokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terrascaler.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.gitlab.tokenKey }}: {{ .Values.gitlab.token | quote }}
{{- end }}
