{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "terrascaler.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.metrics.prometheusRule.namespace }}
  labels:
    {{- include "terrascaler.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: terrascaler.rules
      rules:
        - alert: TerrascalerScaleDownPotential
          expr: terrascaler_scale_down_potential_nodes > 0
          for: {{ .Values.metrics.prometheusRule.for }}
          labels:
            {{- toYaml .Values.metrics.prometheusRule.labels | nindent 12 }}
          annotations:
            {{- toYaml .Values.metrics.prometheusRule.annotations | nindent 12 }}
{{- end }}
