{{- if .Values.clusterRole.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ template "cloudflare-operator.clusterRoleName" . }}
rules:
- apiGroups:
  - cf.containeroo.ch
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cf.containeroo.ch
  resources:
  - accounts/finalizers
  verbs:
  - update
- apiGroups:
  - cf.containeroo.ch
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cf.containeroo.ch
  resources:
  - dnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cf.containeroo.ch
  resources:
  - dnsrecords/finalizers
  verbs:
  - update
- apiGroups:
  - cf.containeroo.ch
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cf.containeroo.ch
  resources:
  - ips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cf.containeroo.ch
  resources:
  - ips/finalizers
  verbs:
  - update
- apiGroups:
  - cf.containeroo.ch
  resources:
  - ips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cf.containeroo.ch
  resources:
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cf.containeroo.ch
  resources:
  - zones/finalizers
  verbs:
  - update
- apiGroups:
  - cf.containeroo.ch
  resources:
  - zones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
{{ if .Values.clusterRole.extraRules }}
  {{- toYaml .Values.clusterRole.extraRules }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cloudflare-operator.clusterRoleName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cloudflare-operator.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "cloudflare-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
