{{- if and .Values.metrics.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "cloudflare-operator.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.metrics.prometheusRule.namespace }}
  labels:
    {{- include "cloudflare-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRule.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: cloudflare-operator
      rules:
        - alert: AccountFailures
          annotations:
            summary: Account {{ "{{ $labels.name }}" }} failed
          expr: cloudflare_operator_account_status > 0
          for: 1m
          labels:
            severity: critical
        - alert: DNSRecordFailures
          annotations:
            summary: DNSRecord {{ "{{ $labels.name }}" }} ({{ "{{ $labels.record_name }}" }}) in namespace {{ "{{ $labels.exported_namespace }}" }} failed
          expr: cloudflare_operator_dns_record_status > 0
          for: 1m
          labels:
            severity: critical
        - alert: IPFailures
          annotations:
            summary: "{{ "{{ $labels.ip_type | title }}" }} IP {{ "{{ $labels.name }}" }} failed"
          expr: cloudflare_operator_ip_status > 0
          for: 1m
          labels:
            severity: critical
        - alert: ZoneFailures
          annotations:
            summary: Zone {{ "{{ $labels.name }}" }} ({{ "{{ $labels.zone_name }}" }}) failed
          expr: cloudflare_operator_zone_status > 0
          for: 1m
          labels:
            severity: critical
{{- end }}
