apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filesystem-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filesystem-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "filesystem-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "filesystem-exporter.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: exporter
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "filesystem-exporter.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-filesystem.path={{ .Values.filesystem.path }}"
            - "-filesystem.report-child-dirs={{ .Values.filesystem.reportChildDirs }}"
            - "-filesystem.scan-concurrency={{ .Values.filesystem.scanConcurrency }}"
            - "-log.level={{ .Values.logLevel }}"
            - "-collector.interval={{ .Values.collector.interval }}"
            - "-collector.timeout={{ .Values.collector.timeout }}"
            - "-web.listen-address=:{{ .Values.metrics.port }}"
            - "-web.metrics-path={{ .Values.metrics.path }}"
          ports:
            - name: http-metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http-metrics
          startupProbe:
            httpGet:
              path: /-/healthy
              port: http-metrics
            periodSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http-metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.filesystem.path }}
              readOnly: {{ .Values.volumeMount.readOnly }}
      volumes:
        - name: data
          {{- if .Values.volume }}
          {{- toYaml .Values.volume | nindent 10 }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
